from __future__ import annotations

import json
import os
from pathlib import Path

from harvest.models import HarvestResult


def _atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(content, encoding="utf-8")
    os.replace(tmp, path)


def _read_env(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    out: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        k, _, v = line.partition("=")
        out[k.strip()] = v.strip()
    return out


def _write_env(path: Path, env: dict[str, str]) -> None:
    lines = ["# Auto-generated by api-harvest", ""]
    for k in sorted(env.keys()):
        lines.append(f"{k}={env[k]}")
    _atomic_write(path, "\n".join(lines) + "\n")


def _read_json(path: Path) -> list[dict]:
    if not path.exists():
        return []
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
        return data if isinstance(data, list) else []
    except json.JSONDecodeError:
        return []


def _write_json(path: Path, results: list[dict]) -> None:
    results = sorted(results, key=lambda r: (r.get("tier", 99), r.get("provider_slug", "")))
    _atomic_write(path, json.dumps(results, indent=2) + "\n")


def _render_md(results: list[dict]) -> str:
    by_tier: dict[int, list[dict]] = {}
    for r in results:
        by_tier.setdefault(int(r.get("tier", 0)), []).append(r)

    out = ["# Harvested API Keys", ""]
    for tier in sorted(by_tier.keys()):
        out.append(f"## Tier {tier}")
        out.append("")
        out.append("| Provider | Status | Env Var | Key (last 4) | Rate Limits | Dashboard | Created |")
        out.append("|---|---|---|---|---|---|---|")
        for r in sorted(by_tier[tier], key=lambda x: x.get("provider_slug", "")):
            key = r.get("api_key") or ""
            tail = f"…{key[-4:]}" if key else "—"
            env = r.get("env_var") or "—"
            rate = (r.get("rate_limits") or "").replace("|", "\\|")[:60]
            dash = r.get("dashboard_url") or ""
            dash_link = f"[link]({dash})" if dash else "—"
            created = (r.get("created_at") or "—")[:19]
            out.append(
                f"| {r['provider_name']} | {r['status']} | `{env}` | `{tail}` | {rate} | {dash_link} | {created} |"
            )
        out.append("")
    return "\n".join(out)


def append_result(result: HarvestResult, *, env_path: Path, json_path: Path, md_path: Path) -> None:
    # .env: only write if we actually have a key + env var
    if result.api_key and result.env_var:
        env = _read_env(env_path)
        env[result.env_var] = result.api_key
        _write_env(env_path, env)

    # keys.json: upsert by slug
    results = _read_json(json_path)
    results = [r for r in results if r.get("provider_slug") != result.provider_slug]
    results.append(result.to_dict())
    _write_json(json_path, results)

    # keys.md: re-render from json
    _atomic_write(md_path, _render_md(results))


def rerender(json_path: Path, env_path: Path, md_path: Path) -> int:
    results = _read_json(json_path)
    env: dict[str, str] = {}
    for r in results:
        if r.get("api_key") and r.get("env_var"):
            env[r["env_var"]] = r["api_key"]
    _write_env(env_path, env)
    _atomic_write(md_path, _render_md(results))
    return len(results)
