"""Output generation module for AI API Key Harvester."""

from datetime import datetime


def generate_markdown(results: list) -> str:
    """Generate markdown string from list of ProviderResult objects.

    Args:
        results: List of ProviderResult objects

    Returns:
        str: Markdown formatted string with API keys and provider details
    """
    # Get today's date in YYYY-MM-DD format
    today = datetime.now().strftime("%Y-%m-%d")

    # Count providers with collected keys
    key_count = sum(1 for r in results if r.key is not None)

    # Start markdown
    lines = [
        f"# AI API Keys — {today}",
        "",
        "> Generated by AI API Key Harvester",
        f"> Providers collected: {key_count}",
        "",
        "## .env Block",
        "",
        "Copy-paste into your `.env` file:",
        "",
        "```env",
    ]

    # Add environment variables for providers with keys
    for result in results:
        if result.key is not None:
            lines.append(f"{result.provider.env_var}={result.key}")

    lines.extend(["```", "", "## Provider Details", ""])

    # Add provider details
    for result in results:
        provider = result.provider

        # Determine status emoji
        if result.key is not None:
            status = "✅"
            status_line = f"### {status} {provider.name}"
        elif result.skipped:
            status = "⏭️"
            status_line = f"### {status} {provider.name} — Skipped (tier not selected)"
            lines.append(status_line)
            lines.append("")
            continue
        else:
            status = "❌"
            status_line = f"### {status} {provider.name} — Skipped by user"
            lines.append(status_line)
            lines.append("")
            continue

        lines.append(status_line)
        lines.append("| Field | Value |")
        lines.append("|-------|-------|")
        lines.append(f"| **Key** | `{result.key}` |")
        lines.append(f"| **Env var** | `{provider.env_var}` |")
        lines.append(f"| **Credits** | {provider.credits} |")
        lines.append(f"| **Rate limits** | {provider.rate_limits} |")

        # Format free_models list
        free_models_str = ", ".join(provider.free_models)
        lines.append(f"| **Free models** | {free_models_str} |")
        lines.append(f"| **Gotchas** | {provider.gotchas} |")
        lines.append("")

    return "\n".join(lines)


def write_output(results: list) -> str:
    """Write api_keys_YYYY-MM-DD.md to current directory.

    Args:
        results: List of ProviderResult objects

    Returns:
        str: The filename written
    """
    today = datetime.now().strftime("%Y-%m-%d")
    filename = f"api_keys_{today}.md"

    markdown_content = generate_markdown(results)

    with open(filename, "w") as f:
        f.write(markdown_content)

    return filename
